
# https://megalinter.io/latest/supported-linters/
ENABLE_LINTERS:
  - ACTION_ACTIONLINT
  - ANSIBLE_ANSIBLE_LINT
  - BASH_SHELLCHECK
  - GO_GOLANGCI_LINT
  - MARKDOWN_MARKDOWNLINT
  - PYTHON_RUFF
  - PROTOBUF_PROTOLINT
  - REPOSITORY_GITLEAKS
  - REPOSITORY_KICS
  - YAML_YAMLLINT
REPOSITORY_KICS_ARGUMENTS: "--fail-on high"
GO_GOLANGCI_LINT_ARGUMENTS: "./tools/gemara2ampel/..."
